name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install

      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: '0.30.1'
          node-version: '20'
          solana-cli-version: '1.18.9'

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899

      - name: Check solana config
        run: solana config get

      - run: pnpm run anchor-build
        shell: bash

      - name: Run local validator
        run: solana-test-validator --deactivate-feature Gz1aLrbeQ4Q6PTSafCZcGWZXz91yVRi7ASFzFEr1U4sa --deactivate-feature 8oBxsYqnCvUTGzgEpxPcnVf7MLbWWPYddE33PftFeBBd --deactivate-feature 2ry7ygxiYURULZCrypHhveanvP5tzZ4toRwVp89oCNSj --deactivate-feature PERzQrt5gBD1XEe2c9XdFWqwgHY3mr7cYWbm5V772V8 --deactivate-feature FuS3FPfJDKSNot99ECLXtp3rueq36hMNStJkPJwWodLh --deactivate-feature 9bn2vTJUsUcnpiZWbu2woSKtTGW3ErZC9ERv88SDqQjK --deactivate-feature 8aXvSuopd1PUj7UhehfXJRg6619RHp8ZvwTyyJHdUYsj --deactivate-feature HTW2pSyErTj4BV6KBM9NZ9VBUJVxt7sacNWcf76wtzb3 --deactivate-feature CGB2jM8pwZkeeiXQ66kBMyBR6Np61mggL7XUsmLjVcrw --deactivate-feature zk1snxsc6Fh3wsGNbbHAJNHiJoYgF29mMnTSusGx5EJ --deactivate-feature G6ANXD6ptCSyNd9znZm7j4dEczAJCfx7Cy43oBx3rKHJ --deactivate-feature DT4n6ABDqs6w4bnfwrXT9rsprcPf6cdDga1egctaPkLC --deactivate-feature EenyoWx9UMXYKpR8mW5Jmfmy2fRjzUtM7NduYMY8bx33 --deactivate-feature wLckV1a64ngtcKPRGU4S4grVTestXjmNjxBjaKZrAcn --deactivate-feature 2Fr57nzzkLYXW695UdDxDeR5fhnZWSttZeZYemrnpGFV --deactivate-feature 2KKG3C6RBnxQo9jVVrbzsoSh41TDXLK7gBc9gduyxSzW --deactivate-feature chaie9S2zVfuxJKNRGkyTDokLwWxx6kD2ZLsqQHaDD8 --deactivate-feature decoMktMcnmiq6t3u7g5BfgcQu91nKZr6RvMYf9z1Jb --deactivate-feature 5TuppMutoyzhUSfuYdhgzD47F92GL1g89KpCZQKqedxP --deactivate-feature C97eKZygrkU4JxJsZdjgbUY7iQR7rKTr4NyDWo2E5pRm --deactivate-feature zkhiy5oLowR7HY4zogXjCjeMXyruLqBwSWH21qcFtnv --deactivate-feature 9LZdXeKGeBV6hRLdxS1rHbHoEUsKqesCC2ZAPTPKJAbK --deactivate-feature mustrekeyysGrhwdiwU42tCadZL8GcBb1i2GYhMopQv --deactivate-feature ffecLRhhakKSGhMuc6Fz2Lnfq4uT9q3iu9ZsNaPLxPc --deactivate-feature 7uZBkJXJ1HkuP6R3MJfZs7mLwymBcDbKdqbF51ZWLier --deactivate-feature CJzY83ggJHqPGDq8VisV3U91jDJLuEaALZooBrXtnnLU --deactivate-feature EaQpmC6GtRssaZ3PCUM5YksGqUdMLeZ46BQXYtHYakDS --deactivate-feature tSynMCspg4xFiCj1v3TDb4c7crMR5tSBhLz4sF7rrNA --deactivate-feature GDH5TVdbTPUpRnXaRyQqiKUa7uZAbZ28Q2N9bhbKoMLm --deactivate-feature 7mScTYkJXsbdrcwTQRs7oeCSXoJm4WjzBsRyf8bCU3Np --deactivate-feature 8U4skmMVnF6k2kMvrWbQuRUT3qQSiTYpSjqmhmgfthZu --deactivate-feature 7bTK6Jis8Xpfrs8ZoUfiMDPazTcdPcTWheZFJTA5Z6X4 --deactivate-feature tvcF6b1TRz353zKuhBjinZkKzjmihXmBAHJdjNYw1sQ --deactivate-feature RfEcA95xnhuwooVAhUUksEJLZBF7xKCLuqrJoqk4Zph --deactivate-feature BZn14Liea52wtBwrXUxTv6vojuTTmfc7XGEDTXrvMD7b --deactivate-feature zkiTNuzBKxrCLMKehzuQeKZyLtX2yvFcEKMML8nExU8 --deactivate-feature zkNLP7EQALfC1TYeB3biDU7akDckj8iPkvh9y2Mt2K3 --deactivate-feature 9onWzzvCzNC2jfhxxeqRgs5q7nFAAKpCUvkj6T6GJK9i --deactivate-feature 4eohviozzEeivk1y9UbrnekbAFMDQyJz5JjA9Y6gyvky --deactivate-feature 3opE3EzAKnUftUDURkzMgwpNgimBAypW1mNDYH4x4Zg7 --deactivate-feature BZ5g4hRbu5hLQQBdPyo2z9icGyJ8Khiyj3QS6dhWijTb --deactivate-feature ed9tNscbWLYBooxWA7FE2B5KHWs8A6sxfY8EzezEcoo --deactivate-feature EBq48m8irRKuE7ZnMTLvLg2UuGSqhe8s8oMqnmja1fJw --deactivate-feature BtVN7YjDzNE6Dk7kTT7YTDgMNUZTNgiSJgsdzAeTg2jF --deactivate-feature CLCoTADvV64PSrnR6QXty6Fwrt9Xc6EdxSJE4wLRePjq --reset &

      - run: pnpm run anchor-test
        shell: bash
